/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
export function Model () {
    const { nodes, materials } = useGLTF(
        "./helmet.glb"
    ) as any;
    return (
        <group dispose={ null }>
            <mesh
                castShadow
                receiveShadow
                geometry={ nodes["node_damagedHelmet_-6514"].geometry }
                material={ materials.Material_MR }
                rotation={ [Math.PI / 2, 0, 0] }
            />
        </group>
    );
}
